site_name: UserMetaPro
site_url: http://user-meta.com
site_description: WordPress plugin for managing users
site_author: Khaled Hossain
site_favicon: favicon.ico
pages:
- Home: index.md
- Action and Filter Hooks:
    - List of action and filter hooks: hooks/list.md
    - Examples: hooks/examples.md
- How To: howto/index.md
theme: bootstrap
